# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/dev/minho_team_pihw

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/dev/minho_team_pihw

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/dev/minho_team_pihw/CMakeFiles /home/pi/dev/minho_team_pihw/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/dev/minho_team_pihw/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named Omni3MD

# Build rule for target.
Omni3MD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Omni3MD
.PHONY : Omni3MD

# fast build rule for target.
Omni3MD/fast:
	$(MAKE) -f CMakeFiles/Omni3MD.dir/build.make CMakeFiles/Omni3MD.dir/build
.PHONY : Omni3MD/fast

#=============================================================================
# Target rules for targets named mcp3k8

# Build rule for target.
mcp3k8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcp3k8
.PHONY : mcp3k8

# fast build rule for target.
mcp3k8/fast:
	$(MAKE) -f CMakeFiles/mcp3k8.dir/build.make CMakeFiles/mcp3k8.dir/build
.PHONY : mcp3k8/fast

src/Omni3MD.o: src/Omni3MD.cpp.o

.PHONY : src/Omni3MD.o

# target to build an object file
src/Omni3MD.cpp.o:
	$(MAKE) -f CMakeFiles/Omni3MD.dir/build.make CMakeFiles/Omni3MD.dir/src/Omni3MD.cpp.o
.PHONY : src/Omni3MD.cpp.o

src/Omni3MD.i: src/Omni3MD.cpp.i

.PHONY : src/Omni3MD.i

# target to preprocess a source file
src/Omni3MD.cpp.i:
	$(MAKE) -f CMakeFiles/Omni3MD.dir/build.make CMakeFiles/Omni3MD.dir/src/Omni3MD.cpp.i
.PHONY : src/Omni3MD.cpp.i

src/Omni3MD.s: src/Omni3MD.cpp.s

.PHONY : src/Omni3MD.s

# target to generate assembly for a file
src/Omni3MD.cpp.s:
	$(MAKE) -f CMakeFiles/Omni3MD.dir/build.make CMakeFiles/Omni3MD.dir/src/Omni3MD.cpp.s
.PHONY : src/Omni3MD.cpp.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.s
.PHONY : src/main.c.s

src/mcp3008.o: src/mcp3008.c.o

.PHONY : src/mcp3008.o

# target to build an object file
src/mcp3008.c.o:
	$(MAKE) -f CMakeFiles/mcp3k8.dir/build.make CMakeFiles/mcp3k8.dir/src/mcp3008.c.o
.PHONY : src/mcp3008.c.o

src/mcp3008.i: src/mcp3008.c.i

.PHONY : src/mcp3008.i

# target to preprocess a source file
src/mcp3008.c.i:
	$(MAKE) -f CMakeFiles/mcp3k8.dir/build.make CMakeFiles/mcp3k8.dir/src/mcp3008.c.i
.PHONY : src/mcp3008.c.i

src/mcp3008.s: src/mcp3008.c.s

.PHONY : src/mcp3008.s

# target to generate assembly for a file
src/mcp3008.c.s:
	$(MAKE) -f CMakeFiles/mcp3k8.dir/build.make CMakeFiles/mcp3k8.dir/src/mcp3008.c.s
.PHONY : src/mcp3008.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... Omni3MD"
	@echo "... mcp3k8"
	@echo "... src/Omni3MD.o"
	@echo "... src/Omni3MD.i"
	@echo "... src/Omni3MD.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mcp3008.o"
	@echo "... src/mcp3008.i"
	@echo "... src/mcp3008.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

